#!/usr/bin/env python3
"""reflect.py — Vega's periodic self-improvement pass.

Two jobs, run on a slow cadence (weekly is plenty):

  1. Calibration (no model needed): read every graded prediction, compute the
     overall hit-rate, a Brier score (how well confidence matched reality), and
     per-confidence-bucket hit-rates. Write _data/calibration.yml so the
     Predictions page can show, in public, whether Vega's confidence is honest.

  2. Playbook update (uses Hermes): hand Vega its full graded record + signal
     scorecard + current playbook, and ask it to rewrite its "Lessons" section:
     3 to 7 durable, concrete lessons. This is the real self-upgrade loop, it
     changes the guidance fed into every future entry.

Usage:
    python tools/reflect.py              # calibration + playbook update, commit
    python tools/reflect.py --no-llm     # calibration only (no Hermes), commit
    python tools/reflect.py --dry-run    # compute + print, write/commit nothing

Env: HERMES_* as in new_entry.py; VEGA_NO_PUSH to skip pushing.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
POSTS = ROOT / "_posts"
METHOD = ROOT / "method"
DATA = ROOT / "_data"

HERMES_BIN = os.environ.get("HERMES_BIN", "hermes")
HERMES_PROVIDER = os.environ.get("HERMES_PROVIDER", "openai-codex")
HERMES_MODEL = os.environ.get("HERMES_MODEL", "gpt-5.5")
TIMEOUT = int(os.environ.get("VEGA_TIMEOUT_SEC", "180"))


def split_fm(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    return m.group(1) if m else None


def fval(fm, key):
    m = re.search(rf"^\s*{key}\s*:\s*(.+)$", fm, re.MULTILINE)
    return m.group(1).strip().strip('"').strip("'") if m else None


def collect_record():
    """Every graded call: date, direction, confidence, outcome, claim, signals."""
    rows = []
    for p in sorted(POSTS.glob("*.md")):
        fm = split_fm(p.read_text(encoding="utf-8"))
        if not fm or "prediction:" not in fm:
            continue
        outcome = (re.search(r"outcome:\s*(\w+)", fm) or [None, "pending"])[1]
        if outcome not in ("hit", "miss"):
            continue
        try:
            conf = float(fval(fm, "confidence"))
        except (TypeError, ValueError):
            conf = None
        claim = (re.search(r'claim:\s*"?(.+?)"?\s*$', fm, re.MULTILINE) or [None, ""])[1]
        sig_m = re.search(r"^\s*signals\s*:\s*\[([^\]]*)\]", fm, re.MULTILINE)
        signals = [s.strip().strip('"').strip("'").lower()
                   for s in sig_m.group(1).split(",")] if sig_m else []
        rows.append({"date": (fval(fm, "date") or "")[:10],
                     "direction": fval(fm, "direction"),
                     "confidence": conf, "outcome": outcome,
                     "claim": claim, "signals": [s for s in signals if s]})
    return rows


def compute_calibration(rows):
    graded = len(rows)
    hits = sum(1 for r in rows if r["outcome"] == "hit")
    rate = round(100 * hits / graded) if graded else 0
    # Brier: mean (confidence - actual)^2, actual = 1 if hit else 0.
    scored = [r for r in rows if r["confidence"] is not None]
    brier = (round(sum((r["confidence"] - (1 if r["outcome"] == "hit" else 0)) ** 2
                       for r in scored) / len(scored), 3) if scored else None)
    buckets = []
    for lo, hi, lbl in ((0.0, 0.5, "low (<50%)"), (0.5, 0.7, "medium (50-70%)"),
                        (0.7, 1.01, "high (70%+)")):
        b = [r for r in scored if lo <= r["confidence"] < hi]
        if b:
            bh = sum(1 for r in b if r["outcome"] == "hit")
            buckets.append({"label": lbl, "n": len(b),
                            "hit_rate": round(100 * bh / len(b))})
    return {"graded": graded, "hits": hits, "misses": graded - hits,
            "hit_rate": rate, "brier": brier, "buckets": buckets}


def write_calibration(cal, dry):
    DATA.mkdir(exist_ok=True)
    lines = ["# Auto-generated by tools/reflect.py. Do not hand-edit.",
             f"graded: {cal['graded']}", f"hits: {cal['hits']}",
             f"misses: {cal['misses']}", f"hit_rate: {cal['hit_rate']}",
             f"brier: {cal['brier'] if cal['brier'] is not None else 'null'}",
             "buckets:"]
    for b in cal["buckets"]:
        lines.append(f"  - label: \"{b['label']}\"")
        lines.append(f"    n: {b['n']}")
        lines.append(f"    hit_rate: {b['hit_rate']}")
    if not cal["buckets"]:
        lines[-1] = "buckets: []"
    out = "\n".join(lines) + "\n"
    print(out)
    if not dry:
        (DATA / "calibration.yml").write_text(out, encoding="utf-8", newline="\n")


def signal_scorecard():
    p = METHOD / "signal_stats.json"
    if not p.exists():
        return "(no signal data yet)"
    try:
        stats = json.loads(p.read_text(encoding="utf-8")) or {}
    except Exception:  # noqa: BLE001
        return "(no signal data yet)"
    out = []
    for sig, d in sorted(stats.items()):
        g = d.get("hit", 0) + d.get("miss", 0)
        if g:
            out.append(f"- {sig}: {round(100 * d.get('hit', 0) / g)}% over {g} graded")
    return "\n".join(out) if out else "(no signal data yet)"


def update_playbook(rows, cal, dry):
    play_path = METHOD / "playbook.md"
    current = play_path.read_text(encoding="utf-8") if play_path.exists() else ""
    record = "\n".join(
        f"- [{r['date']}] {r['direction']} @ {r['confidence']} -> {r['outcome'].upper()} "
        f"(signals: {', '.join(r['signals']) or 'none'}): {r['claim'][:90]}"
        for r in rows) or "(no graded calls yet)"
    prompt = (
        "You are Vega, refining your own forecasting playbook. Below is your current "
        "playbook, your full graded record, your calibration, and your signal scorecard. "
        "Rewrite ONLY the lessons: output 3 to 7 short, concrete, durable lessons, each a "
        "single line starting with '- '. Each lesson must be actionable (name a pattern, a "
        "signal, a condition). No preamble, no headings, no numbering, just the bullet "
        "lines. Never use an em-dash or en-dash; use commas or hyphens.\n\n"
        f"Hit rate: {cal['hit_rate']}% over {cal['graded']} graded. Brier: {cal['brier']}.\n"
        f"Calibration by confidence: {cal['buckets']}\n\n"
        f"Signal scorecard:\n{signal_scorecard()}\n\n"
        f"Your record:\n{record}\n\n"
        f"Current playbook:\n{current}\n"
    )
    cmd = [HERMES_BIN, "chat", "-q", prompt, "--provider", HERMES_PROVIDER,
           "--model", HERMES_MODEL, "-Q"]
    try:
        p = subprocess.run(cmd, check=True, text=True, encoding="utf-8",
                           capture_output=True, timeout=TIMEOUT)
    except FileNotFoundError:
        sys.stderr.write(f"[warn] Hermes not found ({HERMES_BIN}); skipping playbook update.\n")
        return False
    except Exception as e:  # noqa: BLE001
        sys.stderr.write(f"[warn] playbook update failed: {e}\n")
        return False
    lessons = [ln.rstrip() for ln in p.stdout.strip().splitlines() if ln.strip().startswith("-")]
    if "—" in p.stdout or "–" in p.stdout:
        sys.stderr.write("[warn] playbook draft had an em/en-dash; skipping update.\n")
        return False
    if not lessons:
        sys.stderr.write("[warn] no lessons parsed; skipping playbook update.\n")
        return False
    new_lessons = "## Lessons (newest first)\n\n" + "\n".join(lessons) + "\n"
    if "## Lessons" in current:
        updated = re.sub(r"## Lessons.*\Z", new_lessons, current, flags=re.DOTALL)
    else:
        updated = current.rstrip() + "\n\n" + new_lessons
    print("\n--- new playbook lessons ---\n" + "\n".join(lessons) + "\n")
    if not dry:
        play_path.write_text(updated, encoding="utf-8", newline="\n")
    return True


def main():
    ap = argparse.ArgumentParser(description="Vega's self-improvement pass.")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--no-llm", action="store_true", help="calibration only, skip Hermes")
    args = ap.parse_args()
    for s in (sys.stdout, sys.stderr):
        try:
            s.reconfigure(encoding="utf-8")
        except Exception:
            pass

    rows = collect_record()
    cal = compute_calibration(rows)
    print(f"[*] {cal['graded']} graded call(s); hit rate {cal['hit_rate']}%, brier {cal['brier']}.")
    write_calibration(cal, args.dry_run)

    changed = [DATA / "calibration.yml"]
    if not args.no_llm and rows:
        if update_playbook(rows, cal, args.dry_run):
            changed.append(METHOD / "playbook.md")

    if args.dry_run:
        print("[ok] dry run, nothing written or committed.")
        return
    paths = [str(p) for p in changed if p.exists()]
    if paths:
        subprocess.run(["git", "-C", str(ROOT), "add"] + paths, check=True)
        subprocess.run(["git", "-C", str(ROOT), "commit", "-m",
                        "Vega: reflection pass (calibration + playbook)"], check=True)
        if not os.environ.get("VEGA_NO_PUSH"):
            subprocess.run(["git", "-C", str(ROOT), "push"], check=True)
        print(f"[ok] committed reflection ({len(paths)} file(s)).")


if __name__ == "__main__":
    main()
